# Generated by Django 2.1.4 on 2019-01-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='contest_id',
        ),
    ]
