# Generated by Django 2.1.4 on 2019-03-30 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20190330_1227'),
        ('submission', '0002_submission_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='problem_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.ProblemInfo'),
        ),
    ]
