# Generated by Django 2.1.4 on 2019-02-25 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
        ('submission', '0002_auto_20190127_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=5)),
                ('time', models.FloatField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Submission')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Test')),
            ],
        ),
    ]
