# Generated by Django 2.1.4 on 2019-01-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_remove_submission_contest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
