# Generated by Django 2.1.4 on 2019-03-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_submission_problem_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='runinfo',
            name='output',
            field=models.TextField(blank=True),
        ),
    ]
