# Generated by Django 2.1.4 on 2019-01-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='source',
            field=models.TextField(blank=True),
        ),
    ]
