# Generated by Django 2.1.4 on 2019-03-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20190226_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='current_test',
            field=models.IntegerField(default=0),
        ),
    ]
