# Generated by Django 2.1.4 on 2019-03-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_submission_current_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runinfo',
            name='time',
            field=models.FloatField(default=0.0),
        ),
    ]
