# Generated by Django 2.1.4 on 2019-03-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_auto_20190305_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runinfo',
            name='status',
            field=models.SmallIntegerField(default=6),
        ),
    ]
