# Generated by Django 2.1.4 on 2019-03-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_auto_20190305_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_invocation',
            field=models.BooleanField(default=False),
        ),
    ]
