# Generated by Django 2.1.4 on 2019-01-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='contest',
            order_with_respect_to='title',
        ),
    ]
