# Generated by Django 2.1.4 on 2019-03-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='score',
            new_name='points',
        ),
    ]
