# Generated by Django 2.1.4 on 2019-03-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='output',
            field=models.TextField(blank=True),
        ),
    ]
