# Generated by Django 2.1.4 on 2019-01-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='idOfProblem',
            new_name='problem_id',
        ),
    ]
