# Generated by Django 2.1.4 on 2019-01-17 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20190117_2037'),
        ('problem', '0002_auto_20190117_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='contest_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.IntegerField(default=0),
        ),
    ]
