# Generated by Django 2.1.4 on 2019-01-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20190110_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='testset',
            field=models.CharField(default='something', max_length=100),
        ),
    ]
