# Generated by Django 2.1.4 on 2019-03-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_problem_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
