# Generated by Django 2.1.4 on 2019-03-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20190330_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
