# Generated by Django 2.1.4 on 2019-01-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20190114_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('test_id', models.IntegerField()),
            ],
        ),
        migrations.AlterOrderWithRespectTo(
            name='test',
            order_with_respect_to='test_id',
        ),
    ]
