# Generated by Django 2.1.4 on 2019-01-14 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20190114_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
    ]
