# Generated by Django 2.1.4 on 2019-03-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20190330_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='score',
            new_name='points',
        ),
    ]
