# Generated by Django 2.1.4 on 2019-03-30 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_auto_20190330_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygonaccount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
