# Generated by Django 2.1.4 on 2019-01-14 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_auto_20190114_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='testset',
            new_name='testset_name',
        ),
        migrations.AlterField(
            model_name='test',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
    ]
