# Generated by Django 2.1.4 on 2019-01-14 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0009_auto_20190114_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legend', models.TextField()),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('notes', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('time_limit', models.IntegerField()),
                ('memory_limit', models.IntegerField()),
                ('input_file', models.CharField(max_length=100)),
                ('output_file', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
    ]
