# Generated by Django 2.1.4 on 2019-01-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0023_auto_20190114_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Statement'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Test'),
        ),
    ]
