# Generated by Django 2.1.4 on 2019-01-14 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0026_auto_20190114_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='id',
        ),
        migrations.AlterField(
            model_name='statement',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='problem.Problem'),
        ),
        migrations.AlterField(
            model_name='test',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
    ]
