# Generated by Django 2.1.4 on 2019-01-14 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0027_auto_20190114_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statement',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
        migrations.AlterField(
            model_name='test',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
    ]
